version: "3"

services:
  web:
    image: smallfawn/dujiaoka-modify
    environment:
        # - INSTALL=false
         - INSTALL=true
        # - MODIFY=true
    volumes:
      - ./env.conf:/dujiaoka/.env
      - ./uploads:/dujiaoka/public/uploads
      - ./storage:/dujiaoka/storage
      - ./theme/hyper:/dujiaoka/resources/views/hyper
      - ./theme/lang/zh_CN/hyper.php:/dujiaoka/resources/lang/zh_CN/hyper.php
    ports:
      - 56789:80
    restart: always
 
  db:
    image: registry.cn-hangzhou.aliyuncs.com/smallfawn/mariadb:focal
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=YOUR_PASSWORD
      - MYSQL_DATABASE=dujiaoka
      - MYSQL_USER=dujiaoka
      - MYSQL_PASSWORD=YOUR_PASSWORD
    volumes:
      - ./mysql:/var/lib/mysql

  redis:
    image: registry.cn-hangzhou.aliyuncs.com/smallfawn/redis:alpine
    restart: always
    volumes:
      - ./redis:/data
